In [1]:
!pip install plotly pandas plotly.graph_objs
import plotly as py
import pandas as pd

In [2]:
file = pd.read_csv("https://raw.githubusercontent.com/BIOF309/group-project-hacking-pythonistas/master/notebooks/death.csv")
df = pd.DataFrame(file)

In [3]:
df.keys()

Index(['Year', '113 Cause Name', 'Cause Name', 'State', 'Deaths',
       'Age-adjusted Death Rate'],
      dtype='object')

In [4]:
df_reduced = df[["Year","Cause Name",'State',"Deaths"]]

In [5]:
df_reduced_indexed = df_reduced.set_index(df["Cause Name"])

In [6]:
df_reduced_indexed

,Year,Cause Name,State,Deaths
Cause Name,,,,
Unintentional injuries,2016,Unintentional injuries,Alabama,2755
Unintentional injuries,2016,Unintentional injuries,Alaska,439
Unintentional injuries,2016,Unintentional injuries,Arizona,4010
Unintentional injuries,2016,Unintentional injuries,Arkansas,1604
Unintentional injuries,2016,Unintentional injuries,California,13213
Unintentional injuries,2016,Unintentional injuries,Colorado,2880
Unintentional injuries,2016,Unintentional injuries,Connecticut,1978
Unintentional injuries,2016,Unintentional injuries,Delaware,516
Unintentional injuries,2016,Unintentional injuries,District of Columbia,401
Unintentional injuries,2016,Unintentional injuries,Florida,12561
Unintentional injuries,2016,Unintentional injuries,Georgia,4701
Unintentional injuries,2016,Unintentional injuries,Hawaii,577
Unintentional injuries,2016,Unintentional injuries,Idaho,849
Unintentional injuries,2016,Unintentional injuries,Illinois,5508
Unintentional injuries,2016,Unintentional injuries,Indiana,3496
Unintentional injuries,2016,Unintentional injuries,Iowa,1608
Unintentional injuries,2016,Unintentional injuries,Kansas,1444
Unintentional injuries,2016,Unintentional injuries,Kentucky,3194
Unintentional injuries,2016,Unintentional injuries,Louisiana,2710
Unintentional injuries,2016,Unintentional injuries,Maine,909
Unintentional injuries,2016,Unintentional injuries,Maryland,2271
Unintentional injuries,2016,Unintentional injuries,Massachusetts,3831
Unintentional injuries,2016,Unintentional injuries,Michigan,5313
Unintentional injuries,2016,Unintentional injuries,Minnesota,2697
Unintentional injuries,2016,Unintentional injuries,Mississippi,1803
Unintentional injuries,2016,Unintentional injuries,Missouri,3625
Unintentional injuries,2016,Unintentional injuries,Montana,626
Unintentional injuries,2016,Unintentional injuries,Nebraska,772
Unintentional injuries,2016,Unintentional injuries,Nevada,1395
Unintentional injuries,2016,Unintentional injuries,New Hampshire,924
...,...,...,...,...
Unintentional injuries,2011,Unintentional injuries,Wisconsin,2680
Unintentional injuries,2010,Unintentional injuries,Wisconsin,2525
Unintentional injuries,2009,Unintentional injuries,Wisconsin,2449
Unintentional injuries,2008,Unintentional injuries,Wisconsin,2484
Unintentional injuries,2007,Unintentional injuries,Wisconsin,2619
Unintentional injuries,2006,Unintentional injuries,Wisconsin,2524
Unintentional injuries,2005,Unintentional injuries,Wisconsin,2490
Unintentional injuries,2004,Unintentional injuries,Wisconsin,2303
Unintentional injuries,2003,Unintentional injuries,Wisconsin,2345
Unintentional injuries,2002,Unintentional injuries,Wisconsin,2274
Unintentional injuries,2001,Unintentional injuries,Wisconsin,2100
Unintentional injuries,2000,Unintentional injuries,Wisconsin,2159
Unintentional injuries,1999,Unintentional injuries,Wisconsin,1955
Unintentional injuries,2015,Unintentional injuries,Wyoming,400
Unintentional injuries,2014,Unintentional injuries,Wyoming,361
Unintentional injuries,2013,Unintentional injuries,Wyoming,325
Unintentional injuries,2012,Unintentional injuries,Wyoming,308
Unintentional injuries,2011,Unintentional injuries,Wyoming,317
Unintentional injuries,2010,Unintentional injuries,Wyoming,346
Unintentional injuries,2009,Unintentional injuries,Wyoming,299
Unintentional injuries,2008,Unintentional injuries,Wyoming,351
Unintentional injuries,2007,Unintentional injuries,Wyoming,299
Unintentional injuries,2006,Unintentional injuries,Wyoming,306
Unintentional injuries,2005,Unintentional injuries,Wyoming,302
Unintentional injuries,2004,Unintentional injuries,Wyoming,243
Unintentional injuries,2003,Unintentional injuries,Wyoming,273
Unintentional injuries,2002,Unintentional injuries,Wyoming,289
Unintentional injuries,2001,Unintentional injuries,Wyoming,272
Unintentional injuries,2000,Unintentional injuries,Wyoming,245
Unintentional injuries,1999,Unintentional injuries,Wyoming,258

In [7]:
df_causename = df_reduced_indexed.loc["All causes"]

In [8]:
df_causename

            Year  Cause Name      State  Deaths
Cause Name
All causes  2006  All causes     Alaska    3354
All causes  2016  All causes    Alabama   52466
All causes  2015  All causes    Alabama   51909
All causes  2014  All causes    Alabama   50215
All causes  2013  All causes    Alabama   50189
All causes  2012  All causes    Alabama   49301
All causes  2011  All causes    Alabama   48681
All causes  2010  All causes    Alabama   48038
All causes  2009  All causes    Alabama   47470
All causes  2008  All causes    Alabama   47707
All causes  2007  All causes    Alabama   46696
All causes  2006  All causes    Alabama   46977
All causes  2005  All causes    Alabama   47090
All causes  2004  All causes    Alabama   46121
All causes  2003  All causes    Alabama   46716
All causes  2002  All causes    Alabama   46069
All causes  2001  All causes    Alabama   45316
All causes  2000  All causes    Alabama   45062
All causes  1999  All causes    Alabama   44806
All causes  2016  All causes     Alaska    4494
All causes  2015  All causes     Alaska    4316
All causes  2014  All causes     Alaska    4128
All causes  2013  All causes     Alaska    3997
All causes  2012  All causes     Alaska    3912
All causes  2011  All causes     Alaska    3849
All causes  2010  All causes     Alaska    3728
All causes  2009  All causes     Alaska    3618
All causes  2008  All causes     Alaska    3494
All causes  2007  All causes     Alaska    3463
All causes  2005  All causes     Alaska    3168
...          ...         ...        ...     ...
All causes  2010  All causes  Wisconsin   47308
All causes  2009  All causes  Wisconsin   45697
All causes  2008  All causes  Wisconsin   46815
All causes  2007  All causes  Wisconsin   46241
All causes  2006  All causes  Wisconsin   46153
All causes  2005  All causes  Wisconsin   46709
All causes  2004  All causes  Wisconsin   45600
All causes  2003  All causes  Wisconsin   46177
All causes  2002  All causes  Wisconsin   46981
All causes  2001  All causes  Wisconsin   46628
All causes  2000  All causes  Wisconsin   46461
All causes  1999  All causes  Wisconsin   46672
All causes  2016  All causes    Wyoming    4722
All causes  2015  All causes    Wyoming    4778
All causes  2014  All causes    Wyoming    4666
All causes  2013  All causes    Wyoming    4516
All causes  2012  All causes    Wyoming    4481
All causes  2011  All causes    Wyoming    4387
All causes  2010  All causes    Wyoming    4438
All causes  2009  All causes    Wyoming    4283
All causes  2008  All causes    Wyoming    4227
All causes  2007  All causes    Wyoming    4266
All causes  2006  All causes    Wyoming    4311
All causes  2005  All causes    Wyoming    4099
All causes  2004  All causes    Wyoming    3955
All causes  2003  All causes    Wyoming    4172
All causes  2002  All causes    Wyoming    4174
All causes  2001  All causes    Wyoming    4029
All causes  2000  All causes    Wyoming    3920
All causes  1999  All causes    Wyoming    4042

[936 rows x 4 columns]

In [9]:
df_causename_indexed = df_causename.set_index(df_causename["Year"])
df_causename_indexed

      Year  Cause Name      State  Deaths
Year
2006  2006  All causes     Alaska    3354
2016  2016  All causes    Alabama   52466
2015  2015  All causes    Alabama   51909
2014  2014  All causes    Alabama   50215
2013  2013  All causes    Alabama   50189
2012  2012  All causes    Alabama   49301
2011  2011  All causes    Alabama   48681
2010  2010  All causes    Alabama   48038
2009  2009  All causes    Alabama   47470
2008  2008  All causes    Alabama   47707
2007  2007  All causes    Alabama   46696
2006  2006  All causes    Alabama   46977
2005  2005  All causes    Alabama   47090
2004  2004  All causes    Alabama   46121
2003  2003  All causes    Alabama   46716
2002  2002  All causes    Alabama   46069
2001  2001  All causes    Alabama   45316
2000  2000  All causes    Alabama   45062
1999  1999  All causes    Alabama   44806
2016  2016  All causes     Alaska    4494
2015  2015  All causes     Alaska    4316
2014  2014  All causes     Alaska    4128
2013  2013  All causes     Alaska    3997
2012  2012  All causes     Alaska    3912
2011  2011  All causes     Alaska    3849
2010  2010  All causes     Alaska    3728
2009  2009  All causes     Alaska    3618
2008  2008  All causes     Alaska    3494
2007  2007  All causes     Alaska    3463
2005  2005  All causes     Alaska    3168
...    ...         ...        ...     ...
2010  2010  All causes  Wisconsin   47308
2009  2009  All causes  Wisconsin   45697
2008  2008  All causes  Wisconsin   46815
2007  2007  All causes  Wisconsin   46241
2006  2006  All causes  Wisconsin   46153
2005  2005  All causes  Wisconsin   46709
2004  2004  All causes  Wisconsin   45600
2003  2003  All causes  Wisconsin   46177
2002  2002  All causes  Wisconsin   46981
2001  2001  All causes  Wisconsin   46628
2000  2000  All causes  Wisconsin   46461
1999  1999  All causes  Wisconsin   46672
2016  2016  All causes    Wyoming    4722
2015  2015  All causes    Wyoming    4778
2014  2014  All causes    Wyoming    4666
2013  2013  All causes    Wyoming    4516
2012  2012  All causes    Wyoming    4481
2011  2011  All causes    Wyoming    4387
2010  2010  All causes    Wyoming    4438
2009  2009  All causes    Wyoming    4283
2008  2008  All causes    Wyoming    4227
2007  2007  All causes    Wyoming    4266
2006  2006  All causes    Wyoming    4311
2005  2005  All causes    Wyoming    4099
2004  2004  All causes    Wyoming    3955
2003  2003  All causes    Wyoming    4172
2002  2002  All causes    Wyoming    4174
2001  2001  All causes    Wyoming    4029
2000  2000  All causes    Wyoming    3920
1999  1999  All causes    Wyoming    4042

[936 rows x 4 columns]

In [10]:
df_1999 = df_causename_indexed.loc[1999]
df_1999_state = df_1999[["State", "Deaths"]]
df_1999_stateindex = df_1999_state.set_index(df_1999_state["State"])
df_1999_stateindex

                                     State   Deaths
State
Alabama                            Alabama    44806
Alaska                              Alaska     2708
Arizona                            Arizona    40050
Arkansas                          Arkansas    27925
California                      California   229380
Colorado                          Colorado    27114
Connecticut                    Connecticut    29446
Delaware                          Delaware     6666
District of Columbia  District of Columbia     6076
Florida                            Florida   163224
Georgia                            Georgia    62028
Hawaii                              Hawaii     8270
Idaho                                Idaho     9579
Illinois                          Illinois   108436
Indiana                            Indiana    55303
Iowa                                  Iowa    28411
Kansas                              Kansas    24472
Kentucky                          Kentucky    39321
Louisiana                        Louisiana    41238
Maine                                Maine    12261
Maryland                          Maryland    43089
Massachusetts                Massachusetts    55840
Michigan                          Michigan    87232
Minnesota                        Minnesota    38537
Mississippi                    Mississippi    28185
Missouri                          Missouri    55931
Montana                            Montana     8128
Nebraska                          Nebraska    15579
Nevada                              Nevada    15082
New Hampshire                New Hampshire     9537
New Jersey                      New Jersey    73981
New Mexico                      New Mexico    13676
New York                          New York   159927
North Carolina              North Carolina    69600
North Dakota                  North Dakota     6103
Ohio                                  Ohio   108517
Oklahoma                          Oklahoma    34700
Oregon                              Oregon    29422
Pennsylvania                  Pennsylvania   130283
Rhode Island                  Rhode Island     9708
South Carolina              South Carolina    36053
South Dakota                  South Dakota     6953
Tennessee                        Tennessee    53765
Texas                                Texas   146858
United States                United States  2391399
Utah                                  Utah    12058
Vermont                            Vermont     4993
Virginia                          Virginia    55320
Washington                      Washington    43865
West Virginia                West Virginia    21049
Wisconsin                        Wisconsin    46672
Wyoming                            Wyoming     4042

In [11]:
df_1999_noUSA = df_1999_stateindex.drop("United States")
df_1999_noUSA

                                     State  Deaths
State
Alabama                            Alabama   44806
Alaska                              Alaska    2708
Arizona                            Arizona   40050
Arkansas                          Arkansas   27925
California                      California  229380
Colorado                          Colorado   27114
Connecticut                    Connecticut   29446
Delaware                          Delaware    6666
District of Columbia  District of Columbia    6076
Florida                            Florida  163224
Georgia                            Georgia   62028
Hawaii                              Hawaii    8270
Idaho                                Idaho    9579
Illinois                          Illinois  108436
Indiana                            Indiana   55303
Iowa                                  Iowa   28411
Kansas                              Kansas   24472
Kentucky                          Kentucky   39321
Louisiana                        Louisiana   41238
Maine                                Maine   12261
Maryland                          Maryland   43089
Massachusetts                Massachusetts   55840
Michigan                          Michigan   87232
Minnesota                        Minnesota   38537
Mississippi                    Mississippi   28185
Missouri                          Missouri   55931
Montana                            Montana    8128
Nebraska                          Nebraska   15579
Nevada                              Nevada   15082
New Hampshire                New Hampshire    9537
New Jersey                      New Jersey   73981
New Mexico                      New Mexico   13676
New York                          New York  159927
North Carolina              North Carolina   69600
North Dakota                  North Dakota    6103
Ohio                                  Ohio  108517
Oklahoma                          Oklahoma   34700
Oregon                              Oregon   29422
Pennsylvania                  Pennsylvania  130283
Rhode Island                  Rhode Island    9708
South Carolina              South Carolina   36053
South Dakota                  South Dakota    6953
Tennessee                        Tennessee   53765
Texas                                Texas  146858
Utah                                  Utah   12058
Vermont                            Vermont    4993
Virginia                          Virginia   55320
Washington                      Washington   43865
West Virginia                West Virginia   21049
Wisconsin                        Wisconsin   46672
Wyoming                            Wyoming    4042

In [12]:
codes = ["AL","AK","AZ","AR","CA","CO","CT","DC","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA",
         "MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD",
         "TN","TX","UT","VT","VA","WA","WV","WI","WY"]

In [13]:
data = [dict(type ='choropleth',
            colorscale = [[0,"rgb(5, 10, 172)"],[0.35,"rgb(40, 60, 190)"],[0.5,"rgb(70, 100, 245)"],
            [0.6,"rgb(90, 120, 245)"],[0.7,"rgb(106, 137, 247)"],[1,"rgb(220, 220, 220)"]],
            autocolorscale=False,
            reversescale = True,
            locations = codes , 
            z = df_1999_noUSA["Deaths"] , 
            locationmode = "USA-states", 
            text = df_1999_stateindex["Deaths"], 
            marker = dict(line = dict(color = 'rgb(255,255,255)',
            width = 2)),
            colorbar = dict(title = "Total Deaths"))]

layout = dict(title = 'Total Deaths in 1999 by State',
        geo = dict(
            scope='usa',
            projection=dict(type='albers usa'),
            showlakes = True,
            lakecolor = 'rgb(255, 255, 255)'))

fig = dict(data = data, layout = layout)
py.offline.plot(fig, filename ='totaldeaths_1999.html')

'file:///Users/sundarg/totaldeaths_1999.html'

In [14]:
df_2016 = df_causename_indexed.loc[2016]
df_2016_state = df_2016[["State", "Deaths"]]
df_2016_stateindex = df_2016_state.set_index(df_2016_state["State"])
df_2016_stateindex

                                     State   Deaths
State
Alabama                            Alabama    52466
Alaska                              Alaska     4494
Arizona                            Arizona    56645
Arkansas                          Arkansas    31756
California                      California   262240
Colorado                          Colorado    37530
Connecticut                    Connecticut    30543
Delaware                          Delaware     8874
District of Columbia  District of Columbia     5037
Florida                            Florida   197313
Georgia                            Georgia    81428
Hawaii                              Hawaii    10913
Idaho                                Idaho    13366
Illinois                          Illinois   107020
Indiana                            Indiana    63473
Iowa                                  Iowa    29538
Kansas                              Kansas    26245
Kentucky                          Kentucky    47827
Louisiana                        Louisiana    44306
Maine                                Maine    14182
Maryland                          Maryland    48824
Massachusetts                Massachusetts    56961
Michigan                          Michigan    96231
Minnesota                        Minnesota    43078
Mississippi                    Mississippi    31741
Missouri                          Missouri    59873
Montana                            Montana     9905
Nebraska                          Nebraska    16217
Nevada                              Nevada    23902
New Hampshire                New Hampshire    12203
New Jersey                      New Jersey    73155
New Mexico                      New Mexico    18365
New York                          New York   154358
North Carolina              North Carolina    90465
North Dakota                  North Dakota     6242
Ohio                                  Ohio   119572
Oklahoma                          Oklahoma    39276
Oregon                              Oregon    35778
Pennsylvania                  Pennsylvania   133040
Rhode Island                  Rhode Island     9735
South Carolina              South Carolina    48130
South Dakota                  South Dakota     7845
Tennessee                        Tennessee    67857
Texas                                Texas   191966
United States                United States  2319475
Utah                                  Utah    17913
Vermont                            Vermont     5909
Virginia                          Virginia    66473
Washington                      Washington    54769
West Virginia                West Virginia    22732
Wisconsin                        Wisconsin    51815
Wyoming                            Wyoming     4722

In [15]:
df_2016_noUSA = df_2016_stateindex.drop("United States")
df_2016_noUSA

                                     State  Deaths
State
Alabama                            Alabama   52466
Alaska                              Alaska    4494
Arizona                            Arizona   56645
Arkansas                          Arkansas   31756
California                      California  262240
Colorado                          Colorado   37530
Connecticut                    Connecticut   30543
Delaware                          Delaware    8874
District of Columbia  District of Columbia    5037
Florida                            Florida  197313
Georgia                            Georgia   81428
Hawaii                              Hawaii   10913
Idaho                                Idaho   13366
Illinois                          Illinois  107020
Indiana                            Indiana   63473
Iowa                                  Iowa   29538
Kansas                              Kansas   26245
Kentucky                          Kentucky   47827
Louisiana                        Louisiana   44306
Maine                                Maine   14182
Maryland                          Maryland   48824
Massachusetts                Massachusetts   56961
Michigan                          Michigan   96231
Minnesota                        Minnesota   43078
Mississippi                    Mississippi   31741
Missouri                          Missouri   59873
Montana                            Montana    9905
Nebraska                          Nebraska   16217
Nevada                              Nevada   23902
New Hampshire                New Hampshire   12203
New Jersey                      New Jersey   73155
New Mexico                      New Mexico   18365
New York                          New York  154358
North Carolina              North Carolina   90465
North Dakota                  North Dakota    6242
Ohio                                  Ohio  119572
Oklahoma                          Oklahoma   39276
Oregon                              Oregon   35778
Pennsylvania                  Pennsylvania  133040
Rhode Island                  Rhode Island    9735
South Carolina              South Carolina   48130
South Dakota                  South Dakota    7845
Tennessee                        Tennessee   67857
Texas                                Texas  191966
Utah                                  Utah   17913
Vermont                            Vermont    5909
Virginia                          Virginia   66473
Washington                      Washington   54769
West Virginia                West Virginia   22732
Wisconsin                        Wisconsin   51815
Wyoming                            Wyoming    4722

In [16]:
data_2 = [dict(type ='choropleth',
            colorscale = [[0,"rgb(5, 10, 172)"],[0.35,"rgb(40, 60, 190)"],[0.5,"rgb(70, 100, 245)"],
            [0.6,"rgb(90, 120, 245)"],[0.7,"rgb(106, 137, 247)"],[1,"rgb(220, 220, 220)"]],
            autocolorscale=False,
            reversescale = True,
            locations = codes , 
            z = df_2016_noUSA["Deaths"] , 
            locationmode = "USA-states", 
            text = df_2016_stateindex["Deaths"], 
            marker = dict(line = dict(color = 'rgb(255,255,255)',
            width = 2)),
            colorbar = dict(title = "Total Deaths"))]

layout_2 = dict(title = 'Total Deaths in 2016 by State',
        geo = dict(
            scope='usa',
            projection=dict(type='albers usa'),
            showlakes = True,
            lakecolor = 'rgb(255, 255, 255)'))

fig = dict(data = data_2, layout = layout_2)
py.offline.plot(fig, filename ='totaldeaths_2016.html')

'file:///Users/sundarg/totaldeaths_2016.html'

In [17]:
list_diff = df_2016_noUSA["Deaths"]- df_1999_noUSA["Deaths"] 
data_3 = [dict(type ='choropleth',
            colorscale = [[0,"rgb(5, 10, 172)"],[0.35,"rgb(40, 60, 190)"],[0.5,"rgb(70, 100, 245)"],
            [0.6,"rgb(90, 120, 245)"],[0.7,"rgb(106, 137, 247)"],[1,"rgb(220, 220, 220)"]],
            autocolorscale=True,
            reversescale = True,
            locations = codes , 
            z = list_diff , 
            locationmode = "USA-states", 
            text = df_2016_stateindex["Deaths"], 
            marker = dict(line = dict(color = 'rgb(255,255,255)',
            width = 2)),
            colorbar = dict(title = "Total Deaths"))]

layout_3 = dict(title = 'Increase in Deaths by State',
        geo = dict(
            scope='usa',
            projection=dict(type='albers usa'),
            showlakes = True,
            lakecolor = 'rgb(255, 255, 255)'))

fig = dict(data = data_3, layout = layout_3)
py.offline.plot(fig, filename ='totaldeaths_diff.html')

'file:///Users/sundarg/totaldeaths_diff.html'

In [18]:
df_reduced_rate = df[["Year","Cause Name",'State',"Deaths","Age-adjusted Death Rate"]]
df_reduced_indexed_rate = df_reduced_rate.set_index(df["Cause Name"])
df_causename_rate = df_reduced_indexed_rate.loc["All causes"]
df_causename_indexed_rate = df_causename_rate.set_index(df_causename["Year"])
df_2016_rate = df_causename_indexed_rate.loc[2016]
df_2016_state_rate = df_2016_rate[["State", "Deaths", "Age-adjusted Death Rate"]]
df_2016_stateindex_rate = df_2016_state_rate.set_index(df_2016_state_rate["State"])
df_2016_stateindex_rate
df_2016_noUSA_rate = df_2016_stateindex_rate.drop("United States")
df_2016_noUSA_rate

                                     State  Deaths  Age-adjusted Death Rate
State
Alabama                            Alabama   52466                    920.4
Alaska                              Alaska    4494                    745.6
Arizona                            Arizona   56645                    675.8
Arkansas                          Arkansas   31756                    893.2
California                      California  262240                    616.9
Colorado                          Colorado   37530                    669.5
Connecticut                    Connecticut   30543                    654.0
Delaware                          Delaware    8874                    746.2
District of Columbia  District of Columbia    5037                    766.0
Florida                            Florida  197313                    666.6
Georgia                            Georgia   81428                    800.4
Hawaii                              Hawaii   10913                    572.0
Idaho                                Idaho   13366                    725.0
Illinois                          Illinois  107020                    724.3
Indiana                            Indiana   63473                    835.0
Iowa                                  Iowa   29538                    721.1
Kansas                              Kansas   26245                    756.8
Kentucky                          Kentucky   47827                    938.4
Louisiana                        Louisiana   44306                    870.5
Maine                                Maine   14182                    759.0
Maryland                          Maryland   48824                    717.6
Massachusetts                Massachusetts   56961                    669.0
Michigan                          Michigan   96231                    785.4
Minnesota                        Minnesota   43078                    648.1
Mississippi                    Mississippi   31741                    948.9
Missouri                          Missouri   59873                    808.2
Montana                            Montana    9905                    743.2
Nebraska                          Nebraska   16217                    707.0
Nevada                              Nevada   23902                    762.6
New Hampshire                New Hampshire   12203                    721.5
New Jersey                      New Jersey   73155                    668.5
New Mexico                      New Mexico   18365                    753.4
New York                          New York  154358                    640.7
North Carolina              North Carolina   90465                    782.4
North Dakota                  North Dakota    6242                    688.4
Ohio                                  Ohio  119572                    832.3
Oklahoma                          Oklahoma   39276                    888.4
Oregon                              Oregon   35778                    705.9
Pennsylvania                  Pennsylvania  133040                    770.1
Rhode Island                  Rhode Island    9735                    690.1
South Carolina              South Carolina   48130                    829.8
South Dakota                  South Dakota    7845                    719.5
Tennessee                        Tennessee   67857                    886.3
Texas                                Texas  191966                    730.6
Utah                                  Utah   17913                    714.7
Vermont                            Vermont    5909                    712.8
Virginia                          Virginia   66473                    715.5
Washington                      Washington   54769                    672.0
West Virginia                West Virginia   22732                    943.3
Wisconsin                        Wisconsin   51815                    717.9
Wyoming                            Wyoming    4722                    720.9

In [19]:
import plotly.graph_objs as go
trace = [go.Scatter(x=df_2016_noUSA_rate["Deaths"], y=df_2016_noUSA_rate["Age-adjusted Death Rate"],
                    mode = "markers", text =df_2016_noUSA_rate['State'] )]
layout_2 = go.Layout(title = "Deaths vs. Age adjusted Death Rates", hovermode = "closest", 
                     xaxis = dict(title ="Deaths"), 
                     yaxis =dict(title= "Age-adjusted Death Rate")) 
fig_2 = go.Figure(data = trace, layout = layout_2)
py.offline.plot(fig_2, filename ='totaldeaths_V_rate_2016.html')

'file:///Users/sundarg/totaldeaths_V_rate_2016.html'